### PR TITLE
Mention Framework laptop support

### PR DESCRIPTION
**Pull request by svenstaro**
Also fix some grammar.

### CODE REVIEW

**Comment by mikhail-m1** [comment]
thanks for the PR, does Framework laptop need another config file?

**Comment by svenstaro** [comment]
Framework needs `/sys/bus/iio/devices/iio:device0/in_illuminance_raw`.

**Comment by mikhail-m1** [comment]
and what is the backlight level, is it the same as in current config?

**Comment by svenstaro** [comment]
> and what is the backlight level, is it the same as in current config?

I wasn't scientific about it but it "felt" ok.

**Pull request merged**
